name: build and push docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log into the DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Tag image
      run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/myimage:latest" .
      working-directory: docker
    
    - name: Push Docker images to DockerHub
      run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/myimage:latest" .